### ISSUE TITLE
Introduce "easy" interface

### ISSUE THREAD

**Issue by senier** [Componolit/libsparkcrypto#11]
The API of libsparkcrypto is very cumbersome and generally only acceptable for high-security people that are willing to take a lot of pain. Most interfaces use 32 or 64 bit words as their basic data type, which requires a conversion when handling byte-oriented data. To make things worse, endianness must be taken into account all the time.

A new "easy" API is built on top of the existing word-oriented API. All parameters, like keys, cipher text or plain text are represented as byte arrays based on a modular byte type (`mod 2**8`). Where feasible, API calls are consolidated to reduce the steps necessary to perform a cryptographic operation (e.g. move the operation to create an AES key context into the encrypt call).

To ease testing of the API's and reuse of standard test vectors, conversion functions from hexadecimal strings to byte arrays and vice versa are added to the test utilities.

The following API's need to be implemented, including test cases and benchmarks (in order of priority):

- [x] AES256 CBC encryption
- [x] AES256 CBC decryption
- [x] SHA256 hash generation
- [x] HMAC SHA256 PRF generation
- [x] SHA512 hash generation
- [x] SHA384 hash generation
- [x] HMAC SHA512 authenticator generation
- [x] HMAC SHA384 authenticator generation
- [x] HMAC SHA512 authenticator generation
- [x] HMAC SHA256 authenticator generation
- [x] AES192 CBC encryption
- [x] AES192 CBC decryption
- [x] AES128 CBC encryption
- [x] AES128 CBC decryption
- [x] AES256 encryption
- [x] AES256 decryption
- [x] AES128 encryption
- [x] AES128 decryption
- [x] AES192 encryption
- [x] AES192 decryption
- [x] HMAC SHA512 PRF generation
- [x] HMAC SHA384 PRF generation
- [x] HMAC SHA512 PRF generation
- [x] SHA1 hash generation
- [x] HMAC SHA1 authenticator generation
- [x] RIPEMD160 hash generation
- [x] HMAC RIPEMD160 authenticator generation

Not sure whether explicit padding is needed very often now when we allow arbitrary byte arrays in all the crypto functions. In any case, this would be a function and thus the data would be put on the stack.

- [x] Message padding

**Comment by jklmnn** [comment]
I've already created an unconstrained byte array type with some conversion functions for 32 bit word arrays (https://github.com/jklmnn/STOTP/blob/master/src/lsc-byte_arrays.ads). Maybe we can reuse some of the work.

**Comment by senier** [comment]
Thanks! There is [another fragment](https://github.com/Componolit/jwx/blob/master/src/jwx-libsparkcrypto.ads) in JWX. And, Stefan Berghofer sent me the spec of yet another wrapper library they have at secunet internally.

In the first step, we should see what an elegant, easy-to-use API should look like.

**Comment by senier** [comment]
> I've already created an unconstrained byte array type with some conversion functions for 32 bit word arrays (https://github.com/jklmnn/STOTP/blob/master/src/lsc-byte_arrays.ads). Maybe we can reuse some of the work.

Can I use libsparkcrypto's BSD license for your code when integrating it?

**Comment by jklmnn** [comment]
That is fine.

**Comment by senier** [comment]
Thank you!
